// <auto-generated>
// Generated by Ethar.GeoPose.H3.UnitTests/Tools/generate-tables.py from Uber H3 v4.5.0, src/h3lib/include/constants.h. Do not edit by hand.
// </auto-generated>
// <copyright file="Constants.cs" company="Ethar">
// Copyright (c) Ethar. All rights reserved.
// </copyright>

/* Ported from Uber H3 v4.5.0, src/h3lib/include/constants.h. Copyright 2016-2017, 2020 Uber Technologies, Inc. Licensed under the Apache License, Version 2.0. */

namespace Ethar.GeoPose.H3.Tables
{
    /// <summary>
    /// Constants shared by the H3 engine. Names and values are exactly as in constants.h.
    /// </summary>
    internal static class Constants
    {
        /// <summary>
        /// pi
        /// </summary>
        internal const double M_PI = 3.14159265358979323846;

        /// <summary>
        /// pi / 2.0
        /// </summary>
        internal const double M_PI_2 = 1.5707963267948966;

        /// <summary>
        /// 2.0 * PI
        /// </summary>
        internal const double M_2PI = 6.28318530717958647692528676655900576839433;

        /// <summary>
        /// pi / 180
        /// </summary>
        internal const double M_PI_180 = 0.0174532925199432957692369076848861271111;

        /// <summary>
        /// 180 / pi
        /// </summary>
        internal const double M_180_PI = 57.29577951308232087679815481410517033240547;

        /// <summary>
        /// threshold epsilon
        /// </summary>
        internal const double EPSILON = 0.0000000000000001;

        /// <summary>
        /// sqrt(3) / 2.0
        /// </summary>
        internal const double M_SQRT3_2 = 0.8660254037844386467637231707529361834714;

        /// <summary>
        /// sin(60')
        /// </summary>
        internal const double M_SIN60 = M_SQRT3_2;

        /// <summary>
        /// 1/sin(60')
        /// </summary>
        internal const double M_RSIN60 = 1.1547005383792515290182975610039149112953;

        /// <summary>
        /// one third
        /// </summary>
        internal const double M_ONETHIRD = 0.333333333333333333333333333333333333333;

        /// <summary>
        /// one seventh (1/7)
        /// </summary>
        internal const double M_ONESEVENTH = 0.14285714285714285714285714285714285;

        /// <summary>
        /// rotation angle between Class II and Class III resolution axes (asin(sqrt(3.0 / 28.0)))
        /// </summary>
        internal const double M_AP7_ROT_RADS = 0.333473172251832115336090755351601070065900389;

        /// <summary>
        /// sin(M_AP7_ROT_RADS)
        /// </summary>
        internal const double M_SIN_AP7_ROT = 0.3273268353539885718950318;

        /// <summary>
        /// cos(M_AP7_ROT_RADS)
        /// </summary>
        internal const double M_COS_AP7_ROT = 0.9449111825230680680167902;

        /// <summary>
        /// earth radius in kilometers using WGS84 authalic radius
        /// </summary>
        internal const double EARTH_RADIUS_KM = 6371.007180918475;

        /// <summary>
        /// scaling factor from hex2d resolution 0 unit length (or distance between adjacent cell center points on the plane) to gnomonic unit length.
        /// </summary>
        internal const double RES0_U_GNOMONIC = 0.38196601125010500003;

        /// <summary>
        /// INV_RES0_U_GNOMONIC
        /// </summary>
        internal const double INV_RES0_U_GNOMONIC = 2.61803398874989588842;

        /// <summary>
        /// max H3 resolution; H3 version 1 has 16 resolutions, numbered 0 through 15
        /// </summary>
        internal const int MAX_H3_RES = 15;

        /// <summary>
        /// The number of faces on an icosahedron
        /// </summary>
        internal const int NUM_ICOSA_FACES = 20;

        /// <summary>
        /// The number of H3 base cells
        /// </summary>
        internal const int NUM_BASE_CELLS = 122;

        /// <summary>
        /// The number of vertices in a hexagon
        /// </summary>
        internal const int NUM_HEX_VERTS = 6;

        /// <summary>
        /// The number of vertices in a pentagon
        /// </summary>
        internal const int NUM_PENT_VERTS = 5;

        /// <summary>
        /// The number of pentagons per resolution
        /// </summary>
        internal const int NUM_PENTAGONS = 12;

        /// <summary>
        /// H3 index modes
        /// </summary>
        internal const int H3_CELL_MODE = 1;

        /// <summary>
        /// H3_DIRECTEDEDGE_MODE
        /// </summary>
        internal const int H3_DIRECTEDEDGE_MODE = 2;

        /// <summary>
        /// H3_EDGE_MODE
        /// </summary>
        internal const int H3_EDGE_MODE = 3;

        /// <summary>
        /// H3_VERTEX_MODE
        /// </summary>
        internal const int H3_VERTEX_MODE = 4;
    }
}
