// <auto-generated>
// Generated by Ethar.GeoPose.H3.UnitTests/Tools/generate-tables.py from Uber H3 v4.5.0, src/h3lib/include/coordijk.h. Do not edit by hand.
// </auto-generated>
// <copyright file="CoordIjkTables.cs" company="Ethar">
// Copyright (c) Ethar. All rights reserved.
// </copyright>

/* Ported from Uber H3 v4.5.0, src/h3lib/include/coordijk.h. Copyright 2016-2018, 2020-2022, 2026 Uber Technologies, Inc. Licensed under the Apache License, Version 2.0. */

namespace Ethar.GeoPose.H3.Tables
{
    /// <summary>
    /// Lookup tables from coordijk.h: the unit vectors of the seven digits and the digit rotation tables.
    /// </summary>
    internal static class CoordIjkTables
    {
        /// <summary>
        /// CoordIJK unit vectors corresponding to the 7 H3 digits. C name UNIT_VECS.
        /// </summary>
        internal static readonly CoordIjk[] UNIT_VECS = new CoordIjk[]
        {
            new CoordIjk(0, 0, 0), // direction 0
            new CoordIjk(0, 0, 1), // direction 1
            new CoordIjk(0, 1, 0), // direction 2
            new CoordIjk(0, 1, 1), // direction 3
            new CoordIjk(1, 0, 0), // direction 4
            new CoordIjk(1, 0, 1), // direction 5
            new CoordIjk(1, 1, 0), // direction 6
        };

        /// <summary>
        /// Digit after a 60 degree counter-clockwise rotation, indexed by digit. Generated from the switch statement in C function _rotate60ccw.
        /// </summary>
        internal static readonly Direction[] ROTATE60CCW = new Direction[]
        {
            Direction.Center, // Center
            Direction.IkAxes, // KAxes
            Direction.JkAxes, // JAxes
            Direction.KAxes, // JkAxes
            Direction.IjAxes, // IAxes
            Direction.IAxes, // IkAxes
            Direction.JAxes, // IjAxes
            Direction.Invalid, // Invalid
        };

        /// <summary>
        /// Digit after a 60 degree clockwise rotation, indexed by digit. Generated from the switch statement in C function _rotate60cw.
        /// </summary>
        internal static readonly Direction[] ROTATE60CW = new Direction[]
        {
            Direction.Center, // Center
            Direction.JkAxes, // KAxes
            Direction.IjAxes, // JAxes
            Direction.JAxes, // JkAxes
            Direction.IkAxes, // IAxes
            Direction.KAxes, // IkAxes
            Direction.IAxes, // IjAxes
            Direction.Invalid, // Invalid
        };
    }
}
