// <auto-generated>
// Generated by Ethar.GeoPose.H3.UnitTests/Tools/generate-tables.py from Uber H3 v4.5.0, src/h3lib/lib/faceijk.c. Do not edit by hand.
// </auto-generated>
// <copyright file="FaceIjkTables.cs" company="Ethar">
// Copyright (c) Ethar. All rights reserved.
// </copyright>

/* Ported from Uber H3 v4.5.0, src/h3lib/lib/faceijk.c. Copyright 2016-2023, 2026 Uber Technologies, Inc. Licensed under the Apache License, Version 2.0. */

namespace Ethar.GeoPose.H3.Tables
{
    /// <summary>
    /// Icosahedron face lookup tables and constants from faceijk.c.
    /// </summary>
    internal static class FaceIjkTables
    {
        /// <summary>
        /// square root of 7 and inverse square root of 7
        /// </summary>
        internal const double M_SQRT7 = 2.6457513110645905905016157536392604257102;

        /// <summary>
        /// M_RSQRT7
        /// </summary>
        internal const double M_RSQRT7 = 0.37796447300922722721451653623418006081576;

        /// <summary>
        /// Icosahedron face centers in x/y/z on the unit sphere. C name faceCenterPoint[NUM_ICOSA_FACES].
        /// </summary>
        internal static readonly Vec3d[] faceCenterPoint = new Vec3d[]
        {
            new Vec3d(0.2199307791404606, 0.6583691780274996, 0.7198475378926182), // face 0
            new Vec3d(-0.2139234834501421, 0.1478171829550703, 0.9656017935214205), // face 1
            new Vec3d(0.1092625278784797, -0.4811951572873210, 0.8697775121287253), // face 2
            new Vec3d(0.7428567301586791, -0.3593941678278028, 0.5648005936517033), // face 3
            new Vec3d(0.8112534709140969, 0.3448953237639384, 0.4721387736413930), // face 4
            new Vec3d(-0.1055498149613921, 0.9794457296411413, 0.1718874610009365), // face 5
            new Vec3d(-0.8075407579970092, 0.1533552485898818, 0.5695261994882688), // face 6
            new Vec3d(-0.2846148069787907, -0.8644080972654206, 0.4144792552473539), // face 7
            new Vec3d(0.7405621473854482, -0.6673299564565524, -0.0789837646326737), // face 8
            new Vec3d(0.8512303986474293, 0.4722343788582681, -0.2289137388687808), // face 9
            new Vec3d(-0.7405621473854481, 0.6673299564565524, 0.0789837646326737), // face 10
            new Vec3d(-0.8512303986474292, -0.4722343788582682, 0.2289137388687808), // face 11
            new Vec3d(0.1055498149613919, -0.9794457296411413, -0.1718874610009365), // face 12
            new Vec3d(0.8075407579970092, -0.1533552485898819, -0.5695261994882688), // face 13
            new Vec3d(0.2846148069787908, 0.8644080972654204, -0.4144792552473539), // face 14
            new Vec3d(-0.7428567301586791, 0.3593941678278027, -0.5648005936517033), // face 15
            new Vec3d(-0.8112534709140971, -0.3448953237639382, -0.4721387736413930), // face 16
            new Vec3d(-0.2199307791404607, -0.6583691780274996, -0.7198475378926182), // face 17
            new Vec3d(0.2139234834501420, -0.1478171829550704, -0.9656017935214205), // face 18
            new Vec3d(-0.1092625278784796, 0.4811951572873210, -0.8697775121287253), // face 19
        };

        /// <summary>
        /// Icosahedron face ijk axes as azimuth in radians from face center to vertex 0/1/2 respectively. C name faceAxesAzRadsCII[NUM_ICOSA_FACES][3].
        /// </summary>
        internal static readonly double[,] faceAxesAzRadsCII = new double[,]
        {
            { 5.619958268523939882, 3.525563166130744542, 1.431168063737548730 }, // face 0
            { 5.760339081714187279, 3.665943979320991689, 1.571548876927796127 }, // face 1
            { 0.780213654393430055, 4.969003859179821079, 2.874608756786625655 }, // face 2
            { 0.430469363979999913, 4.619259568766391033, 2.524864466373195467 }, // face 3
            { 6.130269123335111400, 4.035874020941915804, 1.941478918548720291 }, // face 4
            { 2.692877706530642877, 0.598482604137447119, 4.787272808923838195 }, // face 5
            { 2.982963003477243874, 0.888567901084048369, 5.077358105870439581 }, // face 6
            { 3.532912002790141181, 1.438516900396945656, 5.627307105183336758 }, // face 7
            { 3.494305004259568154, 1.399909901866372864, 5.588700106652763840 }, // face 8
            { 3.003214169499538391, 0.908819067106342928, 5.097609271892733906 }, // face 9
            { 5.930472956509811562, 3.836077854116615875, 1.741682751723420374 }, // face 10
            { 0.138378484090254847, 4.327168688876645809, 2.232773586483450311 }, // face 11
            { 0.448714947059150361, 4.637505151845541521, 2.543110049452346120 }, // face 12
            { 0.158629650112549365, 4.347419854898940135, 2.253024752505744869 }, // face 13
            { 5.891865957979238535, 3.797470855586042958, 1.703075753192847583 }, // face 14
            { 2.711123289609793325, 0.616728187216597771, 4.805518392002988683 }, // face 15
            { 3.294508837434268316, 1.200113735041072948, 5.388903939827463911 }, // face 16
            { 3.804819692245439833, 1.710424589852244509, 5.899214794638635174 }, // face 17
            { 3.664438879055192436, 1.570043776661997111, 5.758833981448388027 }, // face 18
            { 2.361378999196363184, 0.266983896803167583, 4.455774101589558636 }, // face 19
        };

        /// <summary>
        /// Definition of which faces neighbor each other, indexed by face and quadrant (0 central, 1 IJ, 2 KI, 3 JK). C name faceNeighbors[NUM_ICOSA_FACES][4].
        /// </summary>
        internal static readonly FaceOrientIjk[,] faceNeighbors = new FaceOrientIjk[,]
        {
            {
                // face 0
                new FaceOrientIjk(0, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(4, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(1, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(5, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 1
                new FaceOrientIjk(1, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(0, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(2, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(6, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 2
                new FaceOrientIjk(2, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(1, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(3, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(7, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 3
                new FaceOrientIjk(3, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(2, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(4, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(8, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 4
                new FaceOrientIjk(4, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(3, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(0, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(9, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 5
                new FaceOrientIjk(5, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(10, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(14, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(0, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 6
                new FaceOrientIjk(6, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(11, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(10, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(1, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 7
                new FaceOrientIjk(7, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(12, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(11, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(2, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 8
                new FaceOrientIjk(8, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(13, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(12, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(3, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 9
                new FaceOrientIjk(9, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(14, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(13, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(4, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 10
                new FaceOrientIjk(10, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(5, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(6, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(15, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 11
                new FaceOrientIjk(11, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(6, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(7, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(16, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 12
                new FaceOrientIjk(12, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(7, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(8, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(17, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 13
                new FaceOrientIjk(13, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(8, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(9, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(18, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 14
                new FaceOrientIjk(14, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(9, new CoordIjk(2, 2, 0), 3),
                new FaceOrientIjk(5, new CoordIjk(2, 0, 2), 3),
                new FaceOrientIjk(19, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 15
                new FaceOrientIjk(15, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(16, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(19, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(10, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 16
                new FaceOrientIjk(16, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(17, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(15, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(11, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 17
                new FaceOrientIjk(17, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(18, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(16, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(12, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 18
                new FaceOrientIjk(18, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(19, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(17, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(13, new CoordIjk(0, 2, 2), 3),
            },
            {
                // face 19
                new FaceOrientIjk(19, new CoordIjk(0, 0, 0), 0),
                new FaceOrientIjk(15, new CoordIjk(2, 0, 2), 1),
                new FaceOrientIjk(18, new CoordIjk(2, 2, 0), 5),
                new FaceOrientIjk(14, new CoordIjk(0, 2, 2), 3),
            },
        };

        /// <summary>
        /// Direction from the origin face to the destination face, relative to the origin face's coordinate system, or -1 if not adjacent. Values 1, 2 and 3 are the IJ, KI and JK quadrants. C name adjacentFaceDir[NUM_ICOSA_FACES][NUM_ICOSA_FACES].
        /// </summary>
        internal static readonly int[,] adjacentFaceDir = new int[,]
        {
            { 0, 2, -1, -1, 1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 }, // face 0
            { 1, 0, 2, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 }, // face 1
            { -1, 1, 0, 2, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 }, // face 2
            { -1, -1, 1, 0, 2, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 }, // face 3
            { 2, -1, -1, 1, 0, -1, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 }, // face 4
            { 3, -1, -1, -1, -1, 0, -1, -1, -1, -1, 1, -1, -1, -1, 2, -1, -1, -1, -1, -1 }, // face 5
            { -1, 3, -1, -1, -1, -1, 0, -1, -1, -1, 2, 1, -1, -1, -1, -1, -1, -1, -1, -1 }, // face 6
            { -1, -1, 3, -1, -1, -1, -1, 0, -1, -1, -1, 2, 1, -1, -1, -1, -1, -1, -1, -1 }, // face 7
            { -1, -1, -1, 3, -1, -1, -1, -1, 0, -1, -1, -1, 2, 1, -1, -1, -1, -1, -1, -1 }, // face 8
            { -1, -1, -1, -1, 3, -1, -1, -1, -1, 0, -1, -1, -1, 2, 1, -1, -1, -1, -1, -1 }, // face 9
            { -1, -1, -1, -1, -1, 1, 2, -1, -1, -1, 0, -1, -1, -1, -1, 3, -1, -1, -1, -1 }, // face 10
            { -1, -1, -1, -1, -1, -1, 1, 2, -1, -1, -1, 0, -1, -1, -1, -1, 3, -1, -1, -1 }, // face 11
            { -1, -1, -1, -1, -1, -1, -1, 1, 2, -1, -1, -1, 0, -1, -1, -1, -1, 3, -1, -1 }, // face 12
            { -1, -1, -1, -1, -1, -1, -1, -1, 1, 2, -1, -1, -1, 0, -1, -1, -1, -1, 3, -1 }, // face 13
            { -1, -1, -1, -1, -1, 2, -1, -1, -1, 1, -1, -1, -1, -1, 0, -1, -1, -1, -1, 3 }, // face 14
            { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, -1, -1, 0, 1, -1, -1, 2 }, // face 15
            { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, -1, 2, 0, 1, -1, -1 }, // face 16
            { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, -1, 2, 0, 1, -1 }, // face 17
            { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, -1, 2, 0, 1 }, // face 18
            { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, 1, -1, -1, 2, 0 }, // face 19
        };

        /// <summary>
        /// Overage distance table, indexed by resolution. -1 marks class III resolutions. C name maxDimByCIIres[].
        /// </summary>
        internal static readonly int[] maxDimByCIIres = new int[]
        {
            2, // res 0
            -1, // res 1
            14, // res 2
            -1, // res 3
            98, // res 4
            -1, // res 5
            686, // res 6
            -1, // res 7
            4802, // res 8
            -1, // res 9
            33614, // res 10
            -1, // res 11
            235298, // res 12
            -1, // res 13
            1647086, // res 14
            -1, // res 15
            11529602, // res 16
        };

        /// <summary>
        /// Unit scale distance table, indexed by resolution. -1 marks class III resolutions. C name unitScaleByCIIres[].
        /// </summary>
        internal static readonly int[] unitScaleByCIIres = new int[]
        {
            1, // res 0
            -1, // res 1
            7, // res 2
            -1, // res 3
            49, // res 4
            -1, // res 5
            343, // res 6
            -1, // res 7
            2401, // res 8
            -1, // res 9
            16807, // res 10
            -1, // res 11
            117649, // res 12
            -1, // res 13
            823543, // res 14
            -1, // res 15
            5764801, // res 16
        };
    }
}
