#!/usr/bin/env python3
"""Regenerates the lookup tables in Ethar.GeoPose.H3/Tables from the Uber H3 C sources.

Usage:
    python generate-tables.py <uber-h3-checkout> <Ethar.GeoPose.H3-project-folder>

The script reads constants.h, coordijk.h, baseCells.c and faceijk.c from src/h3lib of the checkout and writes
Constants.cs, CoordIjkTables.cs, BaseCellTables.cs and FaceIjkTables.cs. Numbers are copied as written in the
C source so that no precision is lost. Run it again after upgrading the H3 checkout and review the diff.
"""

import pathlib
import re
import sys

DIRECTION_NAMES = {
    "CENTER_DIGIT": "Center",
    "K_AXES_DIGIT": "KAxes",
    "J_AXES_DIGIT": "JAxes",
    "JK_AXES_DIGIT": "JkAxes",
    "I_AXES_DIGIT": "IAxes",
    "IK_AXES_DIGIT": "IkAxes",
    "IJ_AXES_DIGIT": "IjAxes",
    "INVALID_DIGIT": "Invalid",
}

SYMBOLS = {
    "INVALID_BASE_CELL": "127",
    "IJ": "1",
    "KI": "2",
    "JK": "3",
}

TOKEN = re.compile(r"\{|\}|,|[A-Za-z_][A-Za-z0-9_]*|-?\d+\.\d*(?:[eE][-+]?\d+)?|-?\d+")


def read(root, rel):
    return pathlib.Path(root, rel).read_text(encoding="utf-8")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def copyright_years(text):
    match = re.search(r"Copyright ([0-9, -]+) Uber Technologies, Inc\.", text)
    if not match:
        raise SystemExit("copyright line not found")
    return match.group(1).strip()


def extract_initializer(text, name):
    match = re.search(r"\b" + re.escape(name) + r"\b[^=;{]*=\s*\{", text)
    if not match:
        raise SystemExit("table " + name + " not found")
    start = match.end() - 1
    depth = 0
    for index in range(start, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start:index + 1]
    raise SystemExit("unbalanced braces in " + name)


def parse_nested(text):
    tokens = TOKEN.findall(text)
    position = [0]

    def parse():
        if tokens[position[0]] != "{":
            raise SystemExit("expected { at token " + str(position[0]))
        position[0] += 1
        items = []
        while tokens[position[0]] != "}":
            token = tokens[position[0]]
            if token == "{":
                items.append(parse())
            elif token == ",":
                position[0] += 1
            else:
                items.append(token)
                position[0] += 1
        position[0] += 1
        return items

    return parse()


def table(text, name):
    return parse_nested(extract_initializer(strip_comments(text), name))


def as_int(token):
    token = SYMBOLS.get(token, token)
    if not re.fullmatch(r"-?\d+", token):
        raise SystemExit("not an integer: " + token)
    return token


def as_double(token):
    if not re.fullmatch(r"-?\d+\.\d*(?:[eE][-+]?\d+)?|-?\d+", token):
        raise SystemExit("not a number: " + token)
    return token if "." in token else token + ".0"


def as_bool(token):
    return "true" if as_int(token) != "0" else "false"


def defines(text):
    """Yields (name, value, summary) for every #define with a value, skipping include guards."""
    pattern = re.compile(r"(?:/\*\*(?P<doc>(?:[^*]|\*(?!/))*)\*/\s*)?#define\s+(?P<name>\w+)\s+(?P<value>\S+)")
    for match in pattern.finditer(text):
        name = match.group("name")
        if name.endswith("_H"):
            continue
        doc = match.group("doc") or ""
        doc = " ".join(line.strip(" *") for line in doc.strip().splitlines()).strip()
        doc = doc.replace("**", "").strip()
        yield name, match.group("value"), doc


def header(file_name, source, years, version):
    lines = []
    lines.append("// <auto-generated>")
    lines.append("// Generated by Ethar.GeoPose.H3.UnitTests/Tools/generate-tables.py from Uber H3 " + version + ", " + source + ". Do not edit by hand.")
    lines.append("// </auto-generated>")
    lines.append('// <copyright file="' + file_name + '" company="Ethar">')
    lines.append("// Copyright (c) Ethar. All rights reserved.")
    lines.append("// </copyright>")
    lines.append("")
    lines.append("/* Ported from Uber H3 " + version + ", " + source + ". Copyright " + years + " Uber Technologies, Inc. Licensed under the Apache License, Version 2.0. */")
    lines.append("")
    return lines


def summary(text, indent):
    return [indent + "/// <summary>", indent + "/// " + text, indent + "/// </summary>"]


def write(path, lines):
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote " + str(path))


def generate_constants(root, out, version):
    text = read(root, "src/h3lib/include/constants.h")
    years = copyright_years(text)
    lines = header("Constants.cs", "src/h3lib/include/constants.h", years, version)
    lines.append("namespace Ethar.GeoPose.H3.Tables")
    lines.append("{")
    lines += summary("Constants shared by the H3 engine. Names and values are exactly as in constants.h.", "    ")
    lines.append("    internal static class Constants")
    lines.append("    {")
    first = True
    for name, value, doc in defines(text):
        if not first:
            lines.append("")
        first = False
        lines += summary(doc or name, "        ")
        if re.fullmatch(r"[A-Za-z_]\w*", value):
            lines.append("        internal const double " + name + " = " + value + ";")
        elif re.fullmatch(r"-?\d+", value):
            lines.append("        internal const int " + name + " = " + value + ";")
        else:
            lines.append("        internal const double " + name + " = " + as_double(value) + ";")
    lines.append("    }")
    lines.append("}")
    write(out / "Constants.cs", lines)


def rotation_table(text, function):
    match = re.search(r"static inline Direction " + function + r"\(Direction digit\)\s*\{(.*?)\n\}", text, re.S)
    if not match:
        raise SystemExit(function + " not found")
    mapping = {name: name for name in DIRECTION_NAMES}
    for source, target in re.findall(r"case (\w+):\s*return (\w+);", match.group(1)):
        mapping[source] = target
    ordered = ["CENTER_DIGIT", "K_AXES_DIGIT", "J_AXES_DIGIT", "JK_AXES_DIGIT", "I_AXES_DIGIT", "IK_AXES_DIGIT", "IJ_AXES_DIGIT", "INVALID_DIGIT"]
    return [(DIRECTION_NAMES[name], DIRECTION_NAMES[mapping[name]]) for name in ordered]


def generate_coordijk(root, out, version):
    text = read(root, "src/h3lib/include/coordijk.h")
    years = copyright_years(text)
    lines = header("CoordIjkTables.cs", "src/h3lib/include/coordijk.h", years, version)
    lines.append("namespace Ethar.GeoPose.H3.Tables")
    lines.append("{")
    lines += summary("Lookup tables from coordijk.h: the unit vectors of the seven digits and the digit rotation tables.", "    ")
    lines.append("    internal static class CoordIjkTables")
    lines.append("    {")
    lines += summary("CoordIJK unit vectors corresponding to the 7 H3 digits. C name UNIT_VECS.", "        ")
    lines.append("        internal static readonly CoordIjk[] UNIT_VECS = new CoordIjk[]")
    lines.append("        {")
    for index, item in enumerate(table(text, "UNIT_VECS")):
        lines.append("            new CoordIjk(" + ", ".join(as_int(v) for v in item) + "), // direction " + str(index))
    lines.append("        };")
    for function, field in (("_rotate60ccw", "ROTATE60CCW"), ("_rotate60cw", "ROTATE60CW")):
        lines.append("")
        lines += summary("Digit after a 60 degree " + ("counter-clockwise" if "ccw" in function else "clockwise") + " rotation, indexed by digit. Generated from the switch statement in C function " + function + ".", "        ")
        lines.append("        internal static readonly Direction[] " + field + " = new Direction[]")
        lines.append("        {")
        for source, target in rotation_table(text, function):
            lines.append("            Direction." + target + ", // " + source)
        lines.append("        };")
    lines.append("    }")
    lines.append("}")
    write(out / "CoordIjkTables.cs", lines)


def generate_basecells(root, out, version):
    text = read(root, "src/h3lib/lib/baseCells.c")
    years = copyright_years(text)
    lines = header("BaseCellTables.cs", "src/h3lib/lib/baseCells.c", years, version)
    lines.append("namespace Ethar.GeoPose.H3.Tables")
    lines.append("{")
    lines += summary("Base cell lookup tables from baseCells.c.", "    ")
    lines.append("    internal static class BaseCellTables")
    lines.append("    {")

    lines += summary("Neighboring base cell ID in each IJK direction. 127 indicates there is no neighbor in that direction. C name baseCellNeighbors[NUM_BASE_CELLS][7].", "        ")
    lines.append("        internal static readonly int[,] baseCellNeighbors = new int[,]")
    lines.append("        {")
    for index, row in enumerate(table(text, "baseCellNeighbors")):
        lines.append("            { " + ", ".join(as_int(v) for v in row) + " }, // base cell " + str(index))
    lines.append("        };")

    lines.append("")
    lines += summary("Neighboring base cell rotations in each IJK direction. -1 indicates there is no neighbor in that direction. C name baseCellNeighbor60CCWRots[NUM_BASE_CELLS][7].", "        ")
    lines.append("        internal static readonly int[,] baseCellNeighbor60CCWRots = new int[,]")
    lines.append("        {")
    for index, row in enumerate(table(text, "baseCellNeighbor60CCWRots")):
        lines.append("            { " + ", ".join(as_int(v) for v in row) + " }, // base cell " + str(index))
    lines.append("        };")

    lines.append("")
    lines += summary("Resolution 0 base cell lookup table for each face, indexed by face, i, j, k. Valid coordinates are 0 to 2. C name faceIjkBaseCells[NUM_ICOSA_FACES][3][3][3].", "        ")
    lines.append("        internal static readonly BaseCellRotation[,,,] faceIjkBaseCells = new BaseCellRotation[,,,]")
    lines.append("        {")
    for face, by_i in enumerate(table(text, "faceIjkBaseCells")):
        lines.append("            {")
        lines.append("                // face " + str(face))
        for i, by_j in enumerate(by_i):
            lines.append("                {")
            lines.append("                    // i " + str(i))
            for j, by_k in enumerate(by_j):
                cells = ", ".join("new BaseCellRotation(" + as_int(c[0]) + ", " + as_int(c[1]) + ")" for c in by_k)
                lines.append("                    { " + cells + " }, // j " + str(j))
            lines.append("                },")
        lines.append("            },")
    lines.append("        };")

    lines.append("")
    lines += summary("Resolution 0 base cell data: the home face and ijk+ coordinates on that face, whether the base cell is a pentagon and, for pentagons, the two clockwise offset faces (-1 when none). C name baseCellData[NUM_BASE_CELLS].", "        ")
    lines.append("        internal static readonly BaseCellData[] baseCellData = new BaseCellData[]")
    lines.append("        {")
    for index, item in enumerate(table(text, "baseCellData")):
        home, is_pentagon, offsets = item
        face, ijk = home
        lines.append("            new BaseCellData(new FaceIjk(" + as_int(face) + ", new CoordIjk(" + ", ".join(as_int(v) for v in ijk) + ")), " + as_bool(is_pentagon) + ", " + as_int(offsets[0]) + ", " + as_int(offsets[1]) + "), // base cell " + str(index))
    lines.append("        };")

    lines.append("    }")
    lines.append("}")
    write(out / "BaseCellTables.cs", lines)


def generate_faceijk(root, out, version):
    text = read(root, "src/h3lib/lib/faceijk.c")
    years = copyright_years(text)
    lines = header("FaceIjkTables.cs", "src/h3lib/lib/faceijk.c", years, version)
    lines.append("namespace Ethar.GeoPose.H3.Tables")
    lines.append("{")
    lines += summary("Icosahedron face lookup tables and constants from faceijk.c.", "    ")
    lines.append("    internal static class FaceIjkTables")
    lines.append("    {")

    first = True
    for name, value, doc in defines(text):
        if not first:
            lines.append("")
        first = False
        lines += summary(doc or name, "        ")
        lines.append("        internal const double " + name + " = " + as_double(value) + ";")

    lines.append("")
    lines += summary("Icosahedron face centers in x/y/z on the unit sphere. C name faceCenterPoint[NUM_ICOSA_FACES].", "        ")
    lines.append("        internal static readonly Vec3d[] faceCenterPoint = new Vec3d[]")
    lines.append("        {")
    for index, item in enumerate(table(text, "faceCenterPoint")):
        lines.append("            new Vec3d(" + ", ".join(as_double(v) for v in item) + "), // face " + str(index))
    lines.append("        };")

    lines.append("")
    lines += summary("Icosahedron face ijk axes as azimuth in radians from face center to vertex 0/1/2 respectively. C name faceAxesAzRadsCII[NUM_ICOSA_FACES][3].", "        ")
    lines.append("        internal static readonly double[,] faceAxesAzRadsCII = new double[,]")
    lines.append("        {")
    for index, item in enumerate(table(text, "faceAxesAzRadsCII")):
        lines.append("            { " + ", ".join(as_double(v) for v in item) + " }, // face " + str(index))
    lines.append("        };")

    lines.append("")
    lines += summary("Definition of which faces neighbor each other, indexed by face and quadrant (0 central, 1 IJ, 2 KI, 3 JK). C name faceNeighbors[NUM_ICOSA_FACES][4].", "        ")
    lines.append("        internal static readonly FaceOrientIjk[,] faceNeighbors = new FaceOrientIjk[,]")
    lines.append("        {")
    for face, quadrants in enumerate(table(text, "faceNeighbors")):
        lines.append("            {")
        lines.append("                // face " + str(face))
        for quadrant in quadrants:
            other, translate, rotation = quadrant
            lines.append("                new FaceOrientIjk(" + as_int(other) + ", new CoordIjk(" + ", ".join(as_int(v) for v in translate) + "), " + as_int(rotation) + "),")
        lines.append("            },")
    lines.append("        };")

    lines.append("")
    lines += summary("Direction from the origin face to the destination face, relative to the origin face's coordinate system, or -1 if not adjacent. Values 1, 2 and 3 are the IJ, KI and JK quadrants. C name adjacentFaceDir[NUM_ICOSA_FACES][NUM_ICOSA_FACES].", "        ")
    lines.append("        internal static readonly int[,] adjacentFaceDir = new int[,]")
    lines.append("        {")
    for index, item in enumerate(table(text, "adjacentFaceDir")):
        lines.append("            { " + ", ".join(as_int(v) for v in item) + " }, // face " + str(index))
    lines.append("        };")

    for name, doc in (("maxDimByCIIres", "Overage distance table, indexed by resolution. -1 marks class III resolutions."), ("unitScaleByCIIres", "Unit scale distance table, indexed by resolution. -1 marks class III resolutions.")):
        lines.append("")
        lines += summary(doc + " C name " + name + "[].", "        ")
        lines.append("        internal static readonly int[] " + name + " = new int[]")
        lines.append("        {")
        for index, item in enumerate(table(text, name)):
            lines.append("            " + as_int(item) + ", // res " + str(index))
        lines.append("        };")

    lines.append("    }")
    lines.append("}")
    write(out / "FaceIjkTables.cs", lines)


def main(argv):
    if len(argv) != 3:
        print(__doc__)
        return 2
    root = pathlib.Path(argv[1])
    out = pathlib.Path(argv[2]) / "Tables"
    out.mkdir(parents=True, exist_ok=True)
    version = "v" + pathlib.Path(root, "VERSION").read_text(encoding="utf-8").strip()
    generate_constants(root, out, version)
    generate_coordijk(root, out, version)
    generate_basecells(root, out, version)
    generate_faceijk(root, out, version)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
