name: API Suggestion
description: Propose a change to the public API surface
title: "[API Proposal]: "
labels: [api-suggestion]
body:
  - type: markdown
    attributes:
      value: |
        We welcome API proposals! We have a process to evaluate the value and shape of new API.  Although recognise the majority of the library is governed by the [GeoPose Standard](https://docs.ogc.org/dis/21-056r10/21-056r10.html) and some API changes will need to be rattified by the standards body before being accepted.
  - type: textarea
    id: background
    attributes:
      label: Background and motivation
      description: Please describe the purpose and value of the new API here.
      placeholder: Purpose
    validations:
      required: true
  - type: textarea
    id: api-proposal
    attributes:
      label: API Proposal
      description: |
        Please provide the specific public API signature diff that you are proposing.

      placeholder: API declaration (no method bodies)
      value: |
        ```csharp
        namespace System.Collections.Generic;

        public class MyFancyCollection<T> : IEnumerable<T>
        {
            public void Fancy(T item);
        }
        ```
    validations:
      required: true
  - type: textarea
    id: api-usage
    attributes:
      label: API Usage
      description: |
        Please provide code examples that highlight how the proposed API additions are meant to be consumed. This will help suggest whether the API has the right shape to be functional, performant and usable.
      placeholder: API usage
      value: |
        ```csharp
        // Fancy the value
        var c = new MyFancyCollection<int>();
        c.Fancy(42);

        // Getting the values out
        foreach (var v in c)
            Console.WriteLine(v);
        ```
    validations:
      required: true
  - type: textarea
    id: alternative-designs
    attributes:
      label: Alternative Designs
      description: |
        Please provide alternative designs. This might not be APIs; for example instead of providing new APIs an option might be to change the behavior of an existing API.
      placeholder: Alternative designs
    validations:
      required: false
  - type: textarea
    id: risks
    attributes:
      label: Risks
      description: |
        Please mention any risks that to your knowledge the API proposal might entail, such as breaking changes, performance regressions, etc.
      placeholder: Risks
    validations:
      required: false